name: capstone
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/location.png
     - assets/clock.png
     - assets/paypal.png
     - assets/creditcard.png
     - assets/coin.png
     - assets/loc.png
     - assets/images/six.png
     - assets/images/two.jpg
     - assets/images/one.jpg
     - assets/images/four.png
     - assets/images/three.jpg
     - assets/images/five.png
     - assets/images/images.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
 
